<a href="https://colab.research.google.com/github/Priyam-28/NerdyNeurons/blob/main/Tensorflow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensorflow Basics

In [2]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# Creating tensors with tf.constant()
scalar=tf.constant(7)
scalar.ndim

0

In [3]:
vector=tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [4]:
tensor=tf.constant([[[1,2,3],[4,5,6]]])
tensor


<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [5]:

# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [6]:
changeable_tensor[1].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  3], dtype=int32)>

In [7]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

>4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [8]:
tf.random.set_seed(42) # global level random seed
non_shuffled=tf.constant([[10,7],[3,4],[2,5]])
# Set the operation random seed
tf.random.shuffle(non_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

##Other ways for creatiing tensors


In [9]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

>>**🔑 Note:** A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

In [4]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,
                shape=[2, 4, 3])
numpy_A,A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [11]:
tensor2=tf.ones(shape=[3,2] ,dtype=tf.int32 )
tensor3=tf.constant([[10,7],[3,4]])
tensor2
# tf.matmul(tensor3,tensor3)
tensor2@tensor3


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 11],
       [13, 11],
       [13, 11]], dtype=int32)>

In [12]:

expanded_tensor3 = tf.expand_dims(tensor3, axis=-1)

# Print the original and expanded tensors
print("Original tensor:\n", tensor3)
print("Expanded tensor:\n", expanded_tensor3)


Original tensor:
 tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
Expanded tensor:
 tf.Tensor(
[[[10]
  [ 7]]

 [[ 3]
  [ 4]]], shape=(2, 2, 1), dtype=int32)


In [14]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([10, 38, 49, 70, 59, 58, 33, 90,  8, 51, 18, 47, 85, 58, 10, 62, 53,
       37, 64, 78, 96,  7, 83, 64, 14, 92, 38, 95, 16, 54, 82, 65, 70, 74,
        1, 13, 86, 65, 23, 21, 75, 58, 31, 74, 85, 46, 70, 87, 85, 42])>

In [18]:
tf.reduce_min(E)
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [20]:
# Change H to float32
E = tf.cast(E, dtype=tf.float32)
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([10., 38., 49., 70., 59., 58., 33., 90.,  8., 51., 18., 47., 85.,
       58., 10., 62., 53., 37., 64., 78., 96.,  7., 83., 64., 14., 92.,
       38., 95., 16., 54., 82., 65., 70., 74.,  1., 13., 86., 65., 23.,
       21., 75., 58., 31., 74., 85., 46., 70., 87., 85., 42.],
      dtype=float32)>

##Squaring, log, square root
Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

tf.square() - get the square of every value in a tensor.
tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

In [5]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [7]:
# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [8]:

# Find the square root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [9]:

# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>